# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Heiti')),
                ('location', models.CharField(max_length=150, verbose_name='Staðsetning')),
                ('info', models.TextField()),
                ('starts', models.DateTimeField(verbose_name='Hefst')),
                ('ends', models.DateTimeField(verbose_name='Lýkur')),
                ('arrive_when', models.DateTimeField(blank=True, null=True, verbose_name='Mæting hvenær')),
                ('arrive_where', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mæting hvert')),
                ('registration_starts', models.DateTimeField(verbose_name='Skráning hefst')),
                ('registration_limit', models.IntegerField(choices=[(0, 'Engin takmörk'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=0, verbose_name='Takmarka skráningu')),
            ],
            options={
                'verbose_name': 'Atburður',
                'verbose_name_plural': 'Atburðir',
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_registered', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Atburður')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Notandi')),
            ],
            options={
                'verbose_name': 'Skráning á atburð',
                'verbose_name_plural': 'Skráningar á atburði',
                'ordering': ['time_registered'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([('event', 'user')]),
        ),
    ]
