# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171121_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='using_transportation',
            field=models.BooleanField(default=False, verbose_name='Rútur'),
        ),
    ]
